import {
    owl_video1, owl_video2, owl_video3, owl_video4, owl_video5, owl_video6,
    product_1, product_2,
    slider1_img, slider2_img, slider3_img, slider4_img, slider5_img,
} from "../../assets"

export let lookups = {
    slides: [
        {
            key: 'SLDR1',
            src: slider1_img,
            title: 'crousel item',
            alt: 'none'
        },
        {
            key: 'SLDR2',
            src: slider2_img,
            title: 'crousel item',
            alt: 'none'
        },
        {
            key: 'SLDR3',
            src: slider3_img,
            title: 'crousel item',
            alt: 'none'
        },
        {
            key: 'SLDR4',
            src: slider4_img,
            title: 'crousel item',
            alt: 'none'
        },
        {
            key: 'SLDR5',
            src: slider5_img,
            title: 'crousel item',
            alt: 'none'
        },
    ],
    owlVideos: [
        { key: 'VDL1', src: owl_video1, title: 'show case video', autoplay: false, loop: true, muted: true },
        { key: 'VDL2', src: owl_video2, title: 'show case video', autoplay: false, loop: true, muted: true },
        { key: 'VDL3', src: owl_video3, title: 'show case video', autoplay: false, loop: true, muted: true },
        { key: 'VDL4', src: owl_video4, title: 'show case video', autoplay: false, loop: true, muted: true },
        { key: 'VDL5', src: owl_video5, title: 'show case video', autoplay: false, loop: true, muted: true },
        { key: 'VDL6', src: owl_video6, title: 'show case video', autoplay: false, loop: true, muted: true },
    ],
    productsFeatured: [
        {
            key: 'FPL1',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL2',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL3',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL4',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL5',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL6',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL7',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL8',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
    ],
    products: [
        {
            key: 'FPL1',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL2',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL3',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL4',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL5',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL6',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL7',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL8',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },{
            key: 'FPL9',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL10',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL11',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
        {
            key: 'FPL12',
            imgSrc: product_1,
            imgHoverSrc: product_2,
            imgAlt: "some test alt",
            title: 'This Product is Good',
            isOnSale: true,
            isFeatured: true,
            currency: 'PKR',
            discountPercent: '20',
            originalPrice: '18000',
            discountedPrice: '15000',
            originCountry: 'Pakistan',
            brand: 'NESCOM',
            inStock: true,
            sizes: { xs: true, sm: true, md: true, lg: true, xl: true }
        },
    ],
    productSizes: [
        {
            key: 'sz01',
            name: 'SM',
            title: 'Small',
            id: '11',
            disabled: false,
            isSelected: true
        },
        {
            key: 'sz02',
            name: 'MD',
            title: 'Medium',
            id: '22',
            disabled: false,
            isSelected: false
        },
        {
            key: 'sz03',
            name: 'LG',
            title: 'Large',
            id: '33',
            disabled: false,
            isSelected: false
        },
        {
            key: 'sz04',
            name: 'XL',
            title: 'Extra Large',
            id: '44',
            disabled: false,
            isSelected: false
        }
    ],
    productTypes: [
        {
            key: 'typ011',
            name: 'Unstiched',
            title: 'Unstiched',
            id: '11',
            disabled: false,
            isSelected: true
        },
        {
            key: 'typ022',
            name: 'Stiched',
            title: 'Stiched',
            id: '22',
            disabled: true,
            isSelected: false
        },
    ]
}

export const updateLookups = (name, value) => {
    if (name)
        lookups[name?.trim?.toString()] = value || []
}